Tests
aliaksandra-papkova-brainly/Selenium-Classic-Framework pull request #1
Opened 2021-10-25 10:02 UTC by aliaksandra-papkova-brainly

2021-11-23 15:53 UTC, marcinoleksiak requested changes
Hi, basically a lot of nice job. Read my comments - I know that some of them are against of what you've seen in videos but when you read them you will see that they make sense :)

Some things - like assertions - have to be changed :)

2021-11-23 15:53 UTC, marcinoleksiak commented on pages/authentication_page.py
> +        self.fill(by_locator=self.__AUTHENTICATION_PAGE_EMAIL_FILED, value="username" + random_num + "@testemail.com")
I encourage you to use f-stings in such case :)
so:
`value=f"username{random_num}@testemail.com"`

2021-11-23 15:53 UTC, marcinoleksiak commented on pages/base_page.py
> +
this singletone can be implemented a bit simpler:
```   
    # class __WebDriver:
    #     def __init__(self):
    #         self.driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())

    driver = None

    def __init__(self):
        if not BasePage.driver:
            BasePage.driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
        self.explicitly_wait = WebDriverWait(
            driver=self.driver,
            timeout=10
        )```

no need to add additional internal class

2021-11-23 15:53 UTC, marcinoleksiak commented on pages/base_page.py
> +        return self.driver.find_element(*by_locator)
all methods that use `explicit_wait` can be refactored.
this part: `self.explicitly_wait.until` already returns an element so there's no need to add `self.driver.find_element(*by_locator)` -> we are searching for the element two times.
enough is:
```
    def get_element(self, by_locator):
        element = self.explicitly_wait.until(expected_conditions.presence_of_element_located(by_locator),
                                   message=f"'{by_locator}' element isn't presented on the page")
        # return self.driver.find_element(*by_locator)
        return element
```

do this in all cases please :)

2021-11-23 15:53 UTC, marcinoleksiak commented on pages/cart_page.py
> +        self.get_element(by_locator=self.__CART_PAGE_GOOD)
`check` methods should return booleans - you can take a look at bootcmap video
those booleans should be asserted inside tests

https://brainly.atlassian.net/wiki/spaces/QA/pages/493256814/5.+Selenium+testing.+Classic+framework

2021-11-23 15:53 UTC, marcinoleksiak commented on tests/test_selenium.py
> +        self.search_section.check_if_section_presents_dress()
add assertions in places like this one
`check_if_section_presents_dress()` should return boolean value

2021-11-23 15:53 UTC, marcinoleksiak commented on tests/test_selenium.py
> +        cls.authentication_page = AuthenticationPage()
`authentication_page` is a class variable declared in class setup so no need to re-declare it here :)

2021-11-24 06:04 UTC, marcinoleksiak requested changes
almost here :)

2021-11-24 06:04 UTC, marcinoleksiak commented on pages/base_page.py
> +        self.driver.find_element(*by_locator).click()
the same can be applied here. explicit wait returns an element and then you just execute: `element.click()`

2021-11-24 06:04 UTC, marcinoleksiak commented on pages/base_page.py
> +        self.driver.find_element(*by_locator).send_keys(value)
`element.send_keys()`

2021-11-24 06:04 UTC, marcinoleksiak commented on pages/base_page.py
> +        return self.driver.find_element(*by_locator).click()
`element.click()`

2021-11-24 06:04 UTC, marcinoleksiak commented on pages/cart_page.py
> +        except NoSuchElementException:
not bad :)
but... since you've modified `get_element` method and you're waiting for an element with `explicit wait` that means when selenium won't find it, it throws different exception: `TimeoutException`

2021-11-24 06:58 UTC, aliaksandra-papkova-brainly commented on pages/base_page.py
> +        self.driver.find_element(*by_locator).send_keys(value)
in this case it throws an error 
![image](https://user-images.githubusercontent.com/82141666/143189990-f3684a87-791b-4a1c-b48d-d530b35a6dd6.png)

2021-11-25 06:09 UTC, marcinoleksiak requested changes
I promise that these are two last comments :)

2021-11-25 06:09 UTC, marcinoleksiak commented on tests/test_selenium.py
> +        self.header_section.click_on_logo_button()
I've noticed that you run 
`        self.header_section.click_on_logo_button()`
at the end of every test and there is no assertion related to this. in such case you can place it in
`    def tearDown(self):`
that is executed after each test

2021-11-25 06:09 UTC, marcinoleksiak commented on tests/test_selenium.py
> +        self.header_section.find_5th_element_in_search_dropdown()
these 5 methods looks like `checks` 
if that is the intention then we need assertions here and methods should return booleans

2021-11-25 09:08 UTC, marcinoleksiak approved these changes
good job! :)

2021-11-25 09:11 UTC, merged